### ISSUE TITLE
How can I apply this on applications from Flatpak?

### ISSUE THREAD

**Issue by vollowx** [avanisubbiah/material-you-theme#30]
Such as GNOME Web, I can not change its theme to adw-gtk

**Comment by Radiquum** [comment]
1st, allow flatpak access to the generated theme by this guide in README:
[gtk4](https://github.com/avanishsubbiah/material-you-theme#flatpak)
[gtk3](https://github.com/avanishsubbiah/material-you-theme#flatpak-1)

2nd, \<by my understanding\> Flatpak apps follow the system theme configuration mode Light\Dark, if that's not the case, then it probably using something custom, and you should ask for support in the corresponding application issues
