### ISSUE TITLE
I Want your wallpapers.

### ISSUE THREAD

**Issue by YisuiDenghua** [avanisubbiah/material-you-theme#69]
I want the wallpapers in your demo [screenshot](https://camo.githubusercontent.com/35780173fdba7b18244dd3b2cc0244b596c70d43a6ac4a369022997ed646edc8/68747470733a2f2f692e696d6775722e636f6d2f564c58666f45615f642e776562703f6d617877696474683d323136302673686170653d7468756d6226666964656c6974793d68696768) , could you please send them to me? Thanks.

**Comment by lutzseverino** [comment]
Found it!
![image](https://user-images.githubusercontent.com/28309837/203134076-f32197c9-15fc-41c7-acff-35481ae60db5.png)
Here's a [higher quality](https://wallpaperdump.cf/wp-content/uploads/2020/07/tQZltZwhf_ixdAVN4dtt8sYTUr6Lw0TIVLrfMS2fPcU.png) version.
