### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [avanisubbiah/material-you-theme#79]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by aayushrautela** [comment]
I think its not under development anymore.

**Comment by FrancescoCaracciolo** [comment]
I'm working on it actually

**Comment by RAinb0wStAr9938** [comment]
yea i was wondering the same too

**Comment by Its-Juice** [comment]
I love this extension. Would love to see G45 Support!
